// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Account {
    pub identity: __sdk::Identity,
    pub name: String,
    pub created_at: __sdk::Timestamp,
    pub last_chat_at: __sdk::Timestamp,
}

impl __sdk::InModule for Account {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Account`.
///
/// Provides typed access to columns for query building.
pub struct AccountCols {
    pub identity: __sdk::__query_builder::Col<Account, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Account, String>,
    pub created_at: __sdk::__query_builder::Col<Account, __sdk::Timestamp>,
    pub last_chat_at: __sdk::__query_builder::Col<Account, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Account {
    type Cols = AccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_chat_at: __sdk::__query_builder::Col::new(table_name, "last_chat_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Account`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountIxCols {
    pub identity: __sdk::__query_builder::IxCol<Account, __sdk::Identity>,
    pub name: __sdk::__query_builder::IxCol<Account, String>,
}

impl __sdk::__query_builder::HasIxCols for Account {
    type IxCols = AccountIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Account {}
