// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChatMessage {
    pub id: u64,
    pub world_id: u16,
    pub sender: __sdk::Identity,
    pub sender_name: String,
    pub text: String,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for ChatMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChatMessage`.
///
/// Provides typed access to columns for query building.
pub struct ChatMessageCols {
    pub id: __sdk::__query_builder::Col<ChatMessage, u64>,
    pub world_id: __sdk::__query_builder::Col<ChatMessage, u16>,
    pub sender: __sdk::__query_builder::Col<ChatMessage, __sdk::Identity>,
    pub sender_name: __sdk::__query_builder::Col<ChatMessage, String>,
    pub text: __sdk::__query_builder::Col<ChatMessage, String>,
    pub at: __sdk::__query_builder::Col<ChatMessage, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ChatMessage {
    type Cols = ChatMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChatMessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            sender_name: __sdk::__query_builder::Col::new(table_name, "sender_name"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}

/// Indexed column accessor struct for the table `ChatMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChatMessageIxCols {
    pub id: __sdk::__query_builder::IxCol<ChatMessage, u64>,
    pub world_id: __sdk::__query_builder::IxCol<ChatMessage, u16>,
}

impl __sdk::__query_builder::HasIxCols for ChatMessage {
    type IxCols = ChatMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChatMessageIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            world_id: __sdk::__query_builder::IxCol::new(table_name, "world_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChatMessage {}
