// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chunk_edit_type::ChunkEdit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk_edit`.
///
/// Obtain a handle from the [`ChunkEditTableAccess::chunk_edit`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk_edit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_edit().on_insert(...)`.
pub struct ChunkEditTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChunkEdit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `chunk_edit`.
pub struct ChunkEditTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ChunkEditTableAccessor {
    type Row = ChunkEdit;
    type Handle<'db> = ChunkEditTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.chunk_edit()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk_edit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkEditTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkEditTableHandle`], which mediates access to the table `chunk_edit`.
    fn chunk_edit(&self) -> ChunkEditTableHandle<'_>;
}

impl ChunkEditTableAccess for super::RemoteTables {
    fn chunk_edit(&self) -> ChunkEditTableHandle<'_> {
        ChunkEditTableHandle {
            imp: self.imp.get_table::<ChunkEdit>("chunk_edit"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkEditInsertCallbackId(__sdk::CallbackId);
pub struct ChunkEditDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ChunkEditTableHandle<'ctx> {
    type Row = ChunkEdit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkEdit> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ChunkEditTableHandle<'ctx> {
    type Row = ChunkEdit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkEdit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkEditInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkEditInsertCallbackId {
        ChunkEditInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkEditInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkEditDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkEditDeleteCallbackId {
        ChunkEditDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkEditDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ChunkEditTableHandle<'ctx> {
    type InsertCallbackId = ChunkEditInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkEditInsertCallbackId {
        ChunkEditInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkEditInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ChunkEditTableHandle<'ctx> {
    type DeleteCallbackId = ChunkEditDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkEditDeleteCallbackId {
        ChunkEditDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkEditDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChunkEditUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkEditTableHandle<'ctx> {
    type UpdateCallbackId = ChunkEditUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkEditUpdateCallbackId {
        ChunkEditUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkEditUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ChunkEditTableHandle<'ctx> {
    type UpdateCallbackId = ChunkEditUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkEditUpdateCallbackId {
        ChunkEditUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkEditUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `chunk_edit`,
/// which allows point queries on the field of the same name
/// via the [`ChunkEditIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_edit().id().find(...)`.
pub struct ChunkEditIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChunkEdit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChunkEditTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `chunk_edit`.
    pub fn id(&self) -> ChunkEditIdUnique<'ctx> {
        ChunkEditIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChunkEditIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ChunkEdit> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChunkEdit>("chunk_edit");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChunkEdit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChunkEdit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChunkEdit`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait chunk_editQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChunkEdit`.
    fn chunk_edit(&self) -> __sdk::__query_builder::Table<ChunkEdit>;
}

impl chunk_editQueryTableAccess for __sdk::QueryTableAccessor {
    fn chunk_edit(&self) -> __sdk::__query_builder::Table<ChunkEdit> {
        __sdk::__query_builder::Table::new("chunk_edit")
    }
}
