// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChunkBlob {
    pub chunk_key: u64,
    pub world_id: u16,
    pub cx: i32,
    pub cy: i32,
    pub cz: i32,
    pub payload: Vec<u8>,
    pub version: u32,
    pub edits_through: u64,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ChunkBlob {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChunkBlob`.
///
/// Provides typed access to columns for query building.
pub struct ChunkBlobCols {
    pub chunk_key: __sdk::__query_builder::Col<ChunkBlob, u64>,
    pub world_id: __sdk::__query_builder::Col<ChunkBlob, u16>,
    pub cx: __sdk::__query_builder::Col<ChunkBlob, i32>,
    pub cy: __sdk::__query_builder::Col<ChunkBlob, i32>,
    pub cz: __sdk::__query_builder::Col<ChunkBlob, i32>,
    pub payload: __sdk::__query_builder::Col<ChunkBlob, Vec<u8>>,
    pub version: __sdk::__query_builder::Col<ChunkBlob, u32>,
    pub edits_through: __sdk::__query_builder::Col<ChunkBlob, u64>,
    pub updated_at: __sdk::__query_builder::Col<ChunkBlob, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ChunkBlob {
    type Cols = ChunkBlobCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChunkBlobCols {
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            cx: __sdk::__query_builder::Col::new(table_name, "cx"),
            cy: __sdk::__query_builder::Col::new(table_name, "cy"),
            cz: __sdk::__query_builder::Col::new(table_name, "cz"),
            payload: __sdk::__query_builder::Col::new(table_name, "payload"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            edits_through: __sdk::__query_builder::Col::new(table_name, "edits_through"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ChunkBlob`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChunkBlobIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<ChunkBlob, u64>,
    pub world_id: __sdk::__query_builder::IxCol<ChunkBlob, u16>,
}

impl __sdk::__query_builder::HasIxCols for ChunkBlob {
    type IxCols = ChunkBlobIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChunkBlobIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            world_id: __sdk::__query_builder::IxCol::new(table_name, "world_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChunkBlob {}
