// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChunkEdit {
    pub id: u64,
    pub chunk_key: u64,
    pub voxel: u16,
    pub value: u8,
    pub tick: u64,
    pub by: __sdk::Identity,
}

impl __sdk::InModule for ChunkEdit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChunkEdit`.
///
/// Provides typed access to columns for query building.
pub struct ChunkEditCols {
    pub id: __sdk::__query_builder::Col<ChunkEdit, u64>,
    pub chunk_key: __sdk::__query_builder::Col<ChunkEdit, u64>,
    pub voxel: __sdk::__query_builder::Col<ChunkEdit, u16>,
    pub value: __sdk::__query_builder::Col<ChunkEdit, u8>,
    pub tick: __sdk::__query_builder::Col<ChunkEdit, u64>,
    pub by: __sdk::__query_builder::Col<ChunkEdit, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for ChunkEdit {
    type Cols = ChunkEditCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChunkEditCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            chunk_key: __sdk::__query_builder::Col::new(table_name, "chunk_key"),
            voxel: __sdk::__query_builder::Col::new(table_name, "voxel"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            by: __sdk::__query_builder::Col::new(table_name, "by"),
        }
    }
}

/// Indexed column accessor struct for the table `ChunkEdit`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChunkEditIxCols {
    pub chunk_key: __sdk::__query_builder::IxCol<ChunkEdit, u64>,
    pub id: __sdk::__query_builder::IxCol<ChunkEdit, u64>,
}

impl __sdk::__query_builder::HasIxCols for ChunkEdit {
    type IxCols = ChunkEditIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChunkEditIxCols {
            chunk_key: __sdk::__query_builder::IxCol::new(table_name, "chunk_key"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChunkEdit {}
