// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chunk_blob_type::ChunkBlob;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chunk_blob`.
///
/// Obtain a handle from the [`ChunkBlobTableAccess::chunk_blob`] method on [`super::RemoteTables`],
/// like `ctx.db.chunk_blob()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_blob().on_insert(...)`.
pub struct ChunkBlobTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChunkBlob>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `chunk_blob`.
pub struct ChunkBlobTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ChunkBlobTableAccessor {
    type Row = ChunkBlob;
    type Handle<'db> = ChunkBlobTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.chunk_blob()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chunk_blob`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChunkBlobTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChunkBlobTableHandle`], which mediates access to the table `chunk_blob`.
    fn chunk_blob(&self) -> ChunkBlobTableHandle<'_>;
}

impl ChunkBlobTableAccess for super::RemoteTables {
    fn chunk_blob(&self) -> ChunkBlobTableHandle<'_> {
        ChunkBlobTableHandle {
            imp: self.imp.get_table::<ChunkBlob>("chunk_blob"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChunkBlobInsertCallbackId(__sdk::CallbackId);
pub struct ChunkBlobDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ChunkBlobTableHandle<'ctx> {
    type Row = ChunkBlob;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkBlob> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ChunkBlobTableHandle<'ctx> {
    type Row = ChunkBlob;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChunkBlob> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChunkBlobInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkBlobInsertCallbackId {
        ChunkBlobInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkBlobInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChunkBlobDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkBlobDeleteCallbackId {
        ChunkBlobDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkBlobDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ChunkBlobTableHandle<'ctx> {
    type InsertCallbackId = ChunkBlobInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkBlobInsertCallbackId {
        ChunkBlobInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChunkBlobInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ChunkBlobTableHandle<'ctx> {
    type DeleteCallbackId = ChunkBlobDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChunkBlobDeleteCallbackId {
        ChunkBlobDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChunkBlobDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChunkBlobUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChunkBlobTableHandle<'ctx> {
    type UpdateCallbackId = ChunkBlobUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkBlobUpdateCallbackId {
        ChunkBlobUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkBlobUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ChunkBlobTableHandle<'ctx> {
    type UpdateCallbackId = ChunkBlobUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChunkBlobUpdateCallbackId {
        ChunkBlobUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChunkBlobUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `chunk_key` unique index on the table `chunk_blob`,
/// which allows point queries on the field of the same name
/// via the [`ChunkBlobChunkKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chunk_blob().chunk_key().find(...)`.
pub struct ChunkBlobChunkKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChunkBlob, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChunkBlobTableHandle<'ctx> {
    /// Get a handle on the `chunk_key` unique index on the table `chunk_blob`.
    pub fn chunk_key(&self) -> ChunkBlobChunkKeyUnique<'ctx> {
        ChunkBlobChunkKeyUnique {
            imp: self.imp.get_unique_constraint::<u64>("chunk_key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChunkBlobChunkKeyUnique<'ctx> {
    /// Find the subscribed row whose `chunk_key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ChunkBlob> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChunkBlob>("chunk_blob");
    _table.add_unique_constraint::<u64>("chunk_key", |row| &row.chunk_key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChunkBlob>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChunkBlob>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChunkBlob`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait chunk_blobQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChunkBlob`.
    fn chunk_blob(&self) -> __sdk::__query_builder::Table<ChunkBlob>;
}

impl chunk_blobQueryTableAccess for __sdk::QueryTableAccessor {
    fn chunk_blob(&self) -> __sdk::__query_builder::Table<ChunkBlob> {
        __sdk::__query_builder::Table::new("chunk_blob")
    }
}
