// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::game_server_type::GameServer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_server`.
///
/// Obtain a handle from the [`GameServerTableAccess::game_server`] method on [`super::RemoteTables`],
/// like `ctx.db.game_server()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_server().on_insert(...)`.
pub struct GameServerTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameServer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `game_server`.
pub struct GameServerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for GameServerTableAccessor {
    type Row = GameServer;
    type Handle<'db> = GameServerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.game_server()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_server`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameServerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameServerTableHandle`], which mediates access to the table `game_server`.
    fn game_server(&self) -> GameServerTableHandle<'_>;
}

impl GameServerTableAccess for super::RemoteTables {
    fn game_server(&self) -> GameServerTableHandle<'_> {
        GameServerTableHandle {
            imp: self.imp.get_table::<GameServer>("game_server"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameServerInsertCallbackId(__sdk::CallbackId);
pub struct GameServerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for GameServerTableHandle<'ctx> {
    type Row = GameServer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameServer> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for GameServerTableHandle<'ctx> {
    type Row = GameServer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameServer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameServerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameServerInsertCallbackId {
        GameServerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameServerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameServerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameServerDeleteCallbackId {
        GameServerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameServerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for GameServerTableHandle<'ctx> {
    type InsertCallbackId = GameServerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameServerInsertCallbackId {
        GameServerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameServerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for GameServerTableHandle<'ctx> {
    type DeleteCallbackId = GameServerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameServerDeleteCallbackId {
        GameServerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameServerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GameServerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameServerTableHandle<'ctx> {
    type UpdateCallbackId = GameServerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameServerUpdateCallbackId {
        GameServerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameServerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for GameServerTableHandle<'ctx> {
    type UpdateCallbackId = GameServerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameServerUpdateCallbackId {
        GameServerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameServerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `server_id` unique index on the table `game_server`,
/// which allows point queries on the field of the same name
/// via the [`GameServerServerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_server().server_id().find(...)`.
pub struct GameServerServerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameServer, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameServerTableHandle<'ctx> {
    /// Get a handle on the `server_id` unique index on the table `game_server`.
    pub fn server_id(&self) -> GameServerServerIdUnique<'ctx> {
        GameServerServerIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("server_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameServerServerIdUnique<'ctx> {
    /// Find the subscribed row whose `server_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<GameServer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameServer>("game_server");
    _table.add_unique_constraint::<u32>("server_id", |row| &row.server_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GameServer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameServer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GameServer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait game_serverQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GameServer`.
    fn game_server(&self) -> __sdk::__query_builder::Table<GameServer>;
}

impl game_serverQueryTableAccess for __sdk::QueryTableAccessor {
    fn game_server(&self) -> __sdk::__query_builder::Table<GameServer> {
        __sdk::__query_builder::Table::new("game_server")
    }
}
