// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameServer {
    pub server_id: u32,
    pub name: String,
    pub addr: String,
    pub players: u32,
    pub heartbeat: __sdk::Timestamp,
}

impl __sdk::InModule for GameServer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GameServer`.
///
/// Provides typed access to columns for query building.
pub struct GameServerCols {
    pub server_id: __sdk::__query_builder::Col<GameServer, u32>,
    pub name: __sdk::__query_builder::Col<GameServer, String>,
    pub addr: __sdk::__query_builder::Col<GameServer, String>,
    pub players: __sdk::__query_builder::Col<GameServer, u32>,
    pub heartbeat: __sdk::__query_builder::Col<GameServer, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for GameServer {
    type Cols = GameServerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GameServerCols {
            server_id: __sdk::__query_builder::Col::new(table_name, "server_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            addr: __sdk::__query_builder::Col::new(table_name, "addr"),
            players: __sdk::__query_builder::Col::new(table_name, "players"),
            heartbeat: __sdk::__query_builder::Col::new(table_name, "heartbeat"),
        }
    }
}

/// Indexed column accessor struct for the table `GameServer`.
///
/// Provides typed access to indexed columns for query building.
pub struct GameServerIxCols {
    pub server_id: __sdk::__query_builder::IxCol<GameServer, u32>,
}

impl __sdk::__query_builder::HasIxCols for GameServer {
    type IxCols = GameServerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GameServerIxCols {
            server_id: __sdk::__query_builder::IxCol::new(table_name, "server_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GameServer {}
