// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GrantServerArgs {
    pub identity: __sdk::Identity,
}

impl From<GrantServerArgs> for super::Reducer {
    fn from(args: GrantServerArgs) -> Self {
        Self::GrantServer {
            identity: args.identity,
        }
    }
}

impl __sdk::InModule for GrantServerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `grant_server`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait grant_server {
    /// Request that the remote module invoke the reducer `grant_server` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`grant_server:grant_server_then`] to run a callback after the reducer completes.
    fn grant_server(&self, identity: __sdk::Identity) -> __sdk::Result<()> {
        self.grant_server_then(identity, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `grant_server` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn grant_server_then(
        &self,
        identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl grant_server for super::RemoteReducers {
    fn grant_server_then(
        &self,
        identity: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GrantServerArgs { identity }, callback)
    }
}
