// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkAbsentArgs {
    pub account: String,
}

impl From<MarkAbsentArgs> for super::Reducer {
    fn from(args: MarkAbsentArgs) -> Self {
        Self::MarkAbsent {
            account: args.account,
        }
    }
}

impl __sdk::InModule for MarkAbsentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_absent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_absent {
    /// Request that the remote module invoke the reducer `mark_absent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`mark_absent:mark_absent_then`] to run a callback after the reducer completes.
    fn mark_absent(&self, account: String) -> __sdk::Result<()> {
        self.mark_absent_then(account, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mark_absent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mark_absent_then(
        &self,
        account: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl mark_absent for super::RemoteReducers {
    fn mark_absent_then(
        &self,
        account: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MarkAbsentArgs { account }, callback)
    }
}
