// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.1 (commit 8ecd3c3bac427a49a9d9b13671bf83324afa59ba).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod account_type;
pub mod chat_message_table;
pub mod chat_message_type;
pub mod chunk_blob_table;
pub mod chunk_blob_type;
pub mod game_server_table;
pub mod game_server_type;
pub mod grant_server_reducer;
pub mod heartbeat_presence_reducer;
pub mod heartbeat_reducer;
pub mod link_identity_reducer;
pub mod mark_absent_reducer;
pub mod mark_present_reducer;
pub mod player_profile_table;
pub mod player_profile_type;
pub mod presence_table;
pub mod presence_type;
pub mod put_chunk_blob_reducer;
pub mod reap_timer_type;
pub mod register_account_reducer;
pub mod save_profile_reducer;
pub mod send_chat_reducer;
pub mod server_identity_type;
pub mod set_password_reducer;
pub mod upsert_world_reducer;
pub mod verify_login_reducer;
pub mod world_table;
pub mod world_type;

pub use account_type::Account;
pub use chat_message_table::*;
pub use chat_message_type::ChatMessage;
pub use chunk_blob_table::*;
pub use chunk_blob_type::ChunkBlob;
pub use game_server_table::*;
pub use game_server_type::GameServer;
pub use grant_server_reducer::grant_server;
pub use heartbeat_presence_reducer::heartbeat_presence;
pub use heartbeat_reducer::heartbeat;
pub use link_identity_reducer::link_identity;
pub use mark_absent_reducer::mark_absent;
pub use mark_present_reducer::mark_present;
pub use player_profile_table::*;
pub use player_profile_type::PlayerProfile;
pub use presence_table::*;
pub use presence_type::Presence;
pub use put_chunk_blob_reducer::put_chunk_blob;
pub use reap_timer_type::ReapTimer;
pub use register_account_reducer::register_account;
pub use save_profile_reducer::save_profile;
pub use send_chat_reducer::send_chat;
pub use server_identity_type::ServerIdentity;
pub use set_password_reducer::set_password;
pub use upsert_world_reducer::upsert_world;
pub use verify_login_reducer::verify_login;
pub use world_table::*;
pub use world_type::World;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    GrantServer {
        identity: __sdk::Identity,
    },
    Heartbeat {
        server_id: u32,
        name: String,
        addr: String,
        player_count: u32,
    },
    HeartbeatPresence {
        server_id: u32,
        world_id: u16,
        accounts: Vec<String>,
    },
    LinkIdentity {
        account: String,
        identity: __sdk::Identity,
    },
    MarkAbsent {
        account: String,
    },
    MarkPresent {
        account: String,
        server_id: u32,
        world_id: u16,
    },
    PutChunkBlob {
        key: u64,
        payload: Vec<u8>,
        version: u32,
        writer_epoch: u64,
    },
    RegisterAccount {
        name: String,
        password: String,
    },
    SaveProfile {
        account: String,
        world_id: u16,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        view_radius: u8,
    },
    SendChat {
        world_id: u16,
        text: String,
    },
    SetPassword {
        name: String,
        password: String,
    },
    UpsertWorld {
        world_id: u16,
        name: String,
        seed: i64,
        world_type: u8,
        graph_hash: u64,
        daytime: f32,
    },
    VerifyLogin {
        name: String,
        password: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::GrantServer { .. } => "grant_server",
            Reducer::Heartbeat { .. } => "heartbeat",
            Reducer::HeartbeatPresence { .. } => "heartbeat_presence",
            Reducer::LinkIdentity { .. } => "link_identity",
            Reducer::MarkAbsent { .. } => "mark_absent",
            Reducer::MarkPresent { .. } => "mark_present",
            Reducer::PutChunkBlob { .. } => "put_chunk_blob",
            Reducer::RegisterAccount { .. } => "register_account",
            Reducer::SaveProfile { .. } => "save_profile",
            Reducer::SendChat { .. } => "send_chat",
            Reducer::SetPassword { .. } => "set_password",
            Reducer::UpsertWorld { .. } => "upsert_world",
            Reducer::VerifyLogin { .. } => "verify_login",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::GrantServer { identity } => {
                __sats::bsatn::to_vec(&grant_server_reducer::GrantServerArgs {
                    identity: identity.clone(),
                })
            }
            Reducer::Heartbeat {
                server_id,
                name,
                addr,
                player_count,
            } => __sats::bsatn::to_vec(&heartbeat_reducer::HeartbeatArgs {
                server_id: server_id.clone(),
                name: name.clone(),
                addr: addr.clone(),
                player_count: player_count.clone(),
            }),
            Reducer::HeartbeatPresence {
                server_id,
                world_id,
                accounts,
            } => __sats::bsatn::to_vec(&heartbeat_presence_reducer::HeartbeatPresenceArgs {
                server_id: server_id.clone(),
                world_id: world_id.clone(),
                accounts: accounts.clone(),
            }),
            Reducer::LinkIdentity { account, identity } => {
                __sats::bsatn::to_vec(&link_identity_reducer::LinkIdentityArgs {
                    account: account.clone(),
                    identity: identity.clone(),
                })
            }
            Reducer::MarkAbsent { account } => {
                __sats::bsatn::to_vec(&mark_absent_reducer::MarkAbsentArgs {
                    account: account.clone(),
                })
            }
            Reducer::MarkPresent {
                account,
                server_id,
                world_id,
            } => __sats::bsatn::to_vec(&mark_present_reducer::MarkPresentArgs {
                account: account.clone(),
                server_id: server_id.clone(),
                world_id: world_id.clone(),
            }),
            Reducer::PutChunkBlob {
                key,
                payload,
                version,
                writer_epoch,
            } => __sats::bsatn::to_vec(&put_chunk_blob_reducer::PutChunkBlobArgs {
                key: key.clone(),
                payload: payload.clone(),
                version: version.clone(),
                writer_epoch: writer_epoch.clone(),
            }),
            Reducer::RegisterAccount { name, password } => {
                __sats::bsatn::to_vec(&register_account_reducer::RegisterAccountArgs {
                    name: name.clone(),
                    password: password.clone(),
                })
            }
            Reducer::SaveProfile {
                account,
                world_id,
                x,
                y,
                z,
                yaw,
                view_radius,
            } => __sats::bsatn::to_vec(&save_profile_reducer::SaveProfileArgs {
                account: account.clone(),
                world_id: world_id.clone(),
                x: x.clone(),
                y: y.clone(),
                z: z.clone(),
                yaw: yaw.clone(),
                view_radius: view_radius.clone(),
            }),
            Reducer::SendChat { world_id, text } => {
                __sats::bsatn::to_vec(&send_chat_reducer::SendChatArgs {
                    world_id: world_id.clone(),
                    text: text.clone(),
                })
            }
            Reducer::SetPassword { name, password } => {
                __sats::bsatn::to_vec(&set_password_reducer::SetPasswordArgs {
                    name: name.clone(),
                    password: password.clone(),
                })
            }
            Reducer::UpsertWorld {
                world_id,
                name,
                seed,
                world_type,
                graph_hash,
                daytime,
            } => __sats::bsatn::to_vec(&upsert_world_reducer::UpsertWorldArgs {
                world_id: world_id.clone(),
                name: name.clone(),
                seed: seed.clone(),
                world_type: world_type.clone(),
                graph_hash: graph_hash.clone(),
                daytime: daytime.clone(),
            }),
            Reducer::VerifyLogin { name, password } => {
                __sats::bsatn::to_vec(&verify_login_reducer::VerifyLoginArgs {
                    name: name.clone(),
                    password: password.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    chat_message: __sdk::TableUpdate<ChatMessage>,
    chunk_blob: __sdk::TableUpdate<ChunkBlob>,
    game_server: __sdk::TableUpdate<GameServer>,
    player_profile: __sdk::TableUpdate<PlayerProfile>,
    presence: __sdk::TableUpdate<Presence>,
    world: __sdk::TableUpdate<World>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "chat_message" => db_update
                    .chat_message
                    .append(chat_message_table::parse_table_update(table_update)?),
                "chunk_blob" => db_update
                    .chunk_blob
                    .append(chunk_blob_table::parse_table_update(table_update)?),
                "game_server" => db_update
                    .game_server
                    .append(game_server_table::parse_table_update(table_update)?),
                "player_profile" => db_update
                    .player_profile
                    .append(player_profile_table::parse_table_update(table_update)?),
                "presence" => db_update
                    .presence
                    .append(presence_table::parse_table_update(table_update)?),
                "world" => db_update
                    .world
                    .append(world_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.chat_message = cache
            .apply_diff_to_table::<ChatMessage>("chat_message", &self.chat_message)
            .with_updates_by_pk(|row| &row.id);
        diff.chunk_blob = cache
            .apply_diff_to_table::<ChunkBlob>("chunk_blob", &self.chunk_blob)
            .with_updates_by_pk(|row| &row.chunk_key);
        diff.game_server = cache
            .apply_diff_to_table::<GameServer>("game_server", &self.game_server)
            .with_updates_by_pk(|row| &row.server_id);
        diff.player_profile = cache
            .apply_diff_to_table::<PlayerProfile>("player_profile", &self.player_profile)
            .with_updates_by_pk(|row| &row.account);
        diff.presence = cache
            .apply_diff_to_table::<Presence>("presence", &self.presence)
            .with_updates_by_pk(|row| &row.account);
        diff.world = cache
            .apply_diff_to_table::<World>("world", &self.world)
            .with_updates_by_pk(|row| &row.world_id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "chat_message" => db_update
                    .chat_message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "chunk_blob" => db_update
                    .chunk_blob
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "game_server" => db_update
                    .game_server
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_profile" => db_update
                    .player_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "presence" => db_update
                    .presence
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world" => db_update
                    .world
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "chat_message" => db_update
                    .chat_message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "chunk_blob" => db_update
                    .chunk_blob
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "game_server" => db_update
                    .game_server
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_profile" => db_update
                    .player_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "presence" => db_update
                    .presence
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world" => db_update
                    .world
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    chat_message: __sdk::TableAppliedDiff<'r, ChatMessage>,
    chunk_blob: __sdk::TableAppliedDiff<'r, ChunkBlob>,
    game_server: __sdk::TableAppliedDiff<'r, GameServer>,
    player_profile: __sdk::TableAppliedDiff<'r, PlayerProfile>,
    presence: __sdk::TableAppliedDiff<'r, Presence>,
    world: __sdk::TableAppliedDiff<'r, World>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<ChatMessage>(
            "chat_message",
            &self.chat_message,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ChunkBlob>("chunk_blob", &self.chunk_blob, event);
        callbacks.invoke_table_row_callbacks::<GameServer>("game_server", &self.game_server, event);
        callbacks.invoke_table_row_callbacks::<PlayerProfile>(
            "player_profile",
            &self.player_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Presence>("presence", &self.presence, event);
        callbacks.invoke_table_row_callbacks::<World>("world", &self.world, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        chat_message_table::register_table(client_cache);
        chunk_blob_table::register_table(client_cache);
        game_server_table::register_table(client_cache);
        player_profile_table::register_table(client_cache);
        presence_table::register_table(client_cache);
        world_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "chat_message",
        "chunk_blob",
        "game_server",
        "player_profile",
        "presence",
        "world",
    ];
}
