// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerInventory {
    pub account: String,
    pub items: Vec<u8>,
    pub updated: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerInventory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerInventory`.
///
/// Provides typed access to columns for query building.
pub struct PlayerInventoryCols {
    pub account: __sdk::__query_builder::Col<PlayerInventory, String>,
    pub items: __sdk::__query_builder::Col<PlayerInventory, Vec<u8>>,
    pub updated: __sdk::__query_builder::Col<PlayerInventory, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerInventory {
    type Cols = PlayerInventoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerInventoryCols {
            account: __sdk::__query_builder::Col::new(table_name, "account"),
            items: __sdk::__query_builder::Col::new(table_name, "items"),
            updated: __sdk::__query_builder::Col::new(table_name, "updated"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerInventory`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerInventoryIxCols {
    pub account: __sdk::__query_builder::IxCol<PlayerInventory, String>,
}

impl __sdk::__query_builder::HasIxCols for PlayerInventory {
    type IxCols = PlayerInventoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerInventoryIxCols {
            account: __sdk::__query_builder::IxCol::new(table_name, "account"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerInventory {}
