// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerProfile {
    pub identity: __sdk::Identity,
    pub world_id: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub view_radius: u8,
    pub last_seen: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to columns for query building.
pub struct PlayerProfileCols {
    pub identity: __sdk::__query_builder::Col<PlayerProfile, __sdk::Identity>,
    pub world_id: __sdk::__query_builder::Col<PlayerProfile, u16>,
    pub x: __sdk::__query_builder::Col<PlayerProfile, f32>,
    pub y: __sdk::__query_builder::Col<PlayerProfile, f32>,
    pub z: __sdk::__query_builder::Col<PlayerProfile, f32>,
    pub yaw: __sdk::__query_builder::Col<PlayerProfile, f32>,
    pub view_radius: __sdk::__query_builder::Col<PlayerProfile, u8>,
    pub last_seen: __sdk::__query_builder::Col<PlayerProfile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerProfile {
    type Cols = PlayerProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerProfileCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            view_radius: __sdk::__query_builder::Col::new(table_name, "view_radius"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerProfileIxCols {
    pub identity: __sdk::__query_builder::IxCol<PlayerProfile, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PlayerProfile {
    type IxCols = PlayerProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerProfileIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerProfile {}
