// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PruneEditsArgs {
    pub key: u64,
    pub up_to_id: u64,
}

impl From<PruneEditsArgs> for super::Reducer {
    fn from(args: PruneEditsArgs) -> Self {
        Self::PruneEdits {
            key: args.key,
            up_to_id: args.up_to_id,
        }
    }
}

impl __sdk::InModule for PruneEditsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `prune_edits`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait prune_edits {
    /// Request that the remote module invoke the reducer `prune_edits` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`prune_edits:prune_edits_then`] to run a callback after the reducer completes.
    fn prune_edits(&self, key: u64, up_to_id: u64) -> __sdk::Result<()> {
        self.prune_edits_then(key, up_to_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `prune_edits` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn prune_edits_then(
        &self,
        key: u64,
        up_to_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl prune_edits for super::RemoteReducers {
    fn prune_edits_then(
        &self,
        key: u64,
        up_to_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PruneEditsArgs { key, up_to_id }, callback)
    }
}
