// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PutChunkBlobArgs {
    pub key: u64,
    pub payload: Vec<u8>,
    pub version: u32,
    pub edits_through: u64,
}

impl From<PutChunkBlobArgs> for super::Reducer {
    fn from(args: PutChunkBlobArgs) -> Self {
        Self::PutChunkBlob {
            key: args.key,
            payload: args.payload,
            version: args.version,
            edits_through: args.edits_through,
        }
    }
}

impl __sdk::InModule for PutChunkBlobArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `put_chunk_blob`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait put_chunk_blob {
    /// Request that the remote module invoke the reducer `put_chunk_blob` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`put_chunk_blob:put_chunk_blob_then`] to run a callback after the reducer completes.
    fn put_chunk_blob(
        &self,
        key: u64,
        payload: Vec<u8>,
        version: u32,
        edits_through: u64,
    ) -> __sdk::Result<()> {
        self.put_chunk_blob_then(key, payload, version, edits_through, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `put_chunk_blob` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn put_chunk_blob_then(
        &self,
        key: u64,
        payload: Vec<u8>,
        version: u32,
        edits_through: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl put_chunk_blob for super::RemoteReducers {
    fn put_chunk_blob_then(
        &self,
        key: u64,
        payload: Vec<u8>,
        version: u32,
        edits_through: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PutChunkBlobArgs {
                key,
                payload,
                version,
                edits_through,
            },
            callback,
        )
    }
}
