// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveInventoryArgs {
    pub account: String,
    pub items: Vec<u8>,
}

impl From<SaveInventoryArgs> for super::Reducer {
    fn from(args: SaveInventoryArgs) -> Self {
        Self::SaveInventory {
            account: args.account,
            items: args.items,
        }
    }
}

impl __sdk::InModule for SaveInventoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_inventory`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_inventory {
    /// Request that the remote module invoke the reducer `save_inventory` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_inventory:save_inventory_then`] to run a callback after the reducer completes.
    fn save_inventory(&self, account: String, items: Vec<u8>) -> __sdk::Result<()> {
        self.save_inventory_then(account, items, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `save_inventory` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_inventory_then(
        &self,
        account: String,
        items: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_inventory for super::RemoteReducers {
    fn save_inventory_then(
        &self,
        account: String,
        items: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SaveInventoryArgs { account, items }, callback)
    }
}
