// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveProfileArgs {
    pub account: String,
    pub world_id: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub view_radius: u8,
}

impl From<SaveProfileArgs> for super::Reducer {
    fn from(args: SaveProfileArgs) -> Self {
        Self::SaveProfile {
            account: args.account,
            world_id: args.world_id,
            x: args.x,
            y: args.y,
            z: args.z,
            yaw: args.yaw,
            view_radius: args.view_radius,
        }
    }
}

impl __sdk::InModule for SaveProfileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_profile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_profile {
    /// Request that the remote module invoke the reducer `save_profile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_profile:save_profile_then`] to run a callback after the reducer completes.
    fn save_profile(
        &self,
        account: String,
        world_id: u16,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        view_radius: u8,
    ) -> __sdk::Result<()> {
        self.save_profile_then(account, world_id, x, y, z, yaw, view_radius, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `save_profile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_profile_then(
        &self,
        account: String,
        world_id: u16,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        view_radius: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_profile for super::RemoteReducers {
    fn save_profile_then(
        &self,
        account: String,
        world_id: u16,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        view_radius: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SaveProfileArgs {
                account,
                world_id,
                x,
                y,
                z,
                yaw,
                view_radius,
            },
            callback,
        )
    }
}
