// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ServerIdentity {
    pub identity: __sdk::Identity,
    pub granted_at: __sdk::Timestamp,
}

impl __sdk::InModule for ServerIdentity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ServerIdentity`.
///
/// Provides typed access to columns for query building.
pub struct ServerIdentityCols {
    pub identity: __sdk::__query_builder::Col<ServerIdentity, __sdk::Identity>,
    pub granted_at: __sdk::__query_builder::Col<ServerIdentity, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ServerIdentity {
    type Cols = ServerIdentityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ServerIdentityCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            granted_at: __sdk::__query_builder::Col::new(table_name, "granted_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ServerIdentity`.
///
/// Provides typed access to indexed columns for query building.
pub struct ServerIdentityIxCols {
    pub identity: __sdk::__query_builder::IxCol<ServerIdentity, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ServerIdentity {
    type IxCols = ServerIdentityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ServerIdentityIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ServerIdentity {}
