// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct VerifyLoginArgs {
    pub name: String,
    pub password: String,
}

impl From<VerifyLoginArgs> for super::Reducer {
    fn from(args: VerifyLoginArgs) -> Self {
        Self::VerifyLogin {
            name: args.name,
            password: args.password,
        }
    }
}

impl __sdk::InModule for VerifyLoginArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `verify_login`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait verify_login {
    /// Request that the remote module invoke the reducer `verify_login` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`verify_login:verify_login_then`] to run a callback after the reducer completes.
    fn verify_login(&self, name: String, password: String) -> __sdk::Result<()> {
        self.verify_login_then(name, password, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `verify_login` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn verify_login_then(
        &self,
        name: String,
        password: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl verify_login for super::RemoteReducers {
    fn verify_login_then(
        &self,
        name: String,
        password: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(VerifyLoginArgs { name, password }, callback)
    }
}
