// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct World {
    pub world_id: u16,
    pub name: String,
    pub seed: i64,
    pub world_type: u8,
    pub graph_hash: u64,
    pub daytime: f32,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for World {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `World`.
///
/// Provides typed access to columns for query building.
pub struct WorldCols {
    pub world_id: __sdk::__query_builder::Col<World, u16>,
    pub name: __sdk::__query_builder::Col<World, String>,
    pub seed: __sdk::__query_builder::Col<World, i64>,
    pub world_type: __sdk::__query_builder::Col<World, u8>,
    pub graph_hash: __sdk::__query_builder::Col<World, u64>,
    pub daytime: __sdk::__query_builder::Col<World, f32>,
    pub created_at: __sdk::__query_builder::Col<World, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for World {
    type Cols = WorldCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldCols {
            world_id: __sdk::__query_builder::Col::new(table_name, "world_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            world_type: __sdk::__query_builder::Col::new(table_name, "world_type"),
            graph_hash: __sdk::__query_builder::Col::new(table_name, "graph_hash"),
            daytime: __sdk::__query_builder::Col::new(table_name, "daytime"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `World`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldIxCols {
    pub name: __sdk::__query_builder::IxCol<World, String>,
    pub world_id: __sdk::__query_builder::IxCol<World, u16>,
}

impl __sdk::__query_builder::HasIxCols for World {
    type IxCols = WorldIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
            world_id: __sdk::__query_builder::IxCol::new(table_name, "world_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for World {}
