//! GPU-resident chunk meshing over the pooled caches. A compute shader
//! (`voxel_mesh.wgsl`) greedy-meshes each dirty mesh slot's voxels into its
//! region of the shared packed-quad pool and publishes per-slot indirect draw
//! args — no CPU meshing, no Bevy meshes, no per-chunk buffers or bind groups
//! (see `pool.rs` for the buffers and `world_draw.rs` for the draw).

use bevy::image::{
    ImageAddressMode, ImageFilterMode, ImageLoaderSettings, ImageSampler, ImageSamplerDescriptor,
};
use bevy::prelude::*;
use bevy::render::extract_resource::{ExtractResource, ExtractResourcePlugin};
use bevy::asset::RenderAssetUsages;
use bevy::render::render_asset::RenderAssets;
use bevy::render::render_resource::binding_types::{
    storage_buffer_read_only_sized, storage_buffer_sized,
};
use bevy::render::render_resource::{
    BindGroup, BindGroupEntries, BindGroupLayoutDescriptor, BindGroupLayoutEntries, BufferUsages,
    CachedComputePipelineId, ComputePassDescriptor, ComputePipelineDescriptor, PipelineCache,
    RawBufferVec, ShaderStages,
};
use bevy::core_pipeline::schedule::camera_driver;
use bevy::render::renderer::{
    RenderContext, RenderDevice, RenderGraph, RenderGraphSystems, RenderQueue,
};
use bevy::render::storage::{GpuShaderBuffer, ShaderBuffer};
use bevy::render::{Render, RenderApp, RenderStartup, RenderSystems};

use crate::chunk::Blocks;
use crate::pool::{ChunkPools, ExtractedPoolOps};

/// Number of tiles stacked in `assets/blocks_mega.png` (= layers of the block
/// texture array). Must match the tile registry in `scripts/gen_textures.mjs`.
pub const MEGA_LAYERS: u32 = 24;

/// The block texture array: `assets/blocks_mega.png` is one 1024²
/// mega-tile per atlas tile index, stacked vertically, generated by
/// `scripts/gen_textures.mjs`. It is loaded main-world-only, reinterpreted as
/// a `MEGA_LAYERS`-layer array once decoded ([`promote_block_textures`]), and
/// only then handed to the render world as `world_draw::ExtractedAtlas`.
/// Handing over the flat 2D image would create a 1024×24576 GPU texture —
/// over the 16384 limit on most devices — and the once-built terrain bind
/// group could capture that 2D view.
#[derive(Resource)]
pub struct AtlasAssets {
    pub texture: Handle<Image>,
    pub promoted: bool,
}

/// The block-faces table buffer (`vec4<u32>` rows), extracted to the render world.
#[derive(Resource, Clone, ExtractResource)]
pub struct FacesTable(pub Handle<ShaderBuffer>);

pub struct GpuMeshPlugin;

impl Plugin for GpuMeshPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(ExtractResourcePlugin::<FacesTable>::default())
            .add_systems(Startup, setup_gpu_assets)
            .add_systems(Update, promote_block_textures);

        let Some(render_app) = app.get_sub_app_mut(RenderApp) else {
            return;
        };
        render_app
            .add_systems(RenderStartup, init_pipeline)
            .add_systems(Render, prepare_jobs.in_set(RenderSystems::PrepareBindGroups))
            // Bevy 0.19 replaced the render graph with schedules: passes are
            // plain systems in the root `RenderGraph` schedule, ordered by
            // system relations rather than node edges. Meshing must land
            // before the cameras draw.
            .add_systems(
                RenderGraph,
                voxel_mesh_pass.in_set(RenderGraphSystems::Render).before(camera_driver),
            );
    }
}

/// The 16x16-tile icon atlas. Load it only through [`load_atlas`].
///
/// Since the terrain moved to [`MEGA_ATLAS_PATH`] this is no longer what
/// clothes a voxel face: it is the art behind the inventory icons and the
/// dropped-item cubes, which slice it as a fixed 8x8 grid of 16x16 tiles
/// (`inventory/mod.rs`). It is hand-maintained — `scripts/gen_textures.mjs`
/// regenerates the mega atlas only.
pub const ATLAS_PATH: &str = "blocks.png";

/// Nearest in every direction: the tiles are 16x16 pixel-art, magnified hard
/// into an icon or onto a dropped cube's face, and linear filtering both blurs
/// them and bleeds the neighbouring tile across the cell edge.
fn atlas_settings(s: &mut ImageLoaderSettings) {
    s.sampler = ImageSampler::nearest();
}

/// Load the block atlas, sampled nearest.
///
/// Every caller must come through here. `AssetServer` keys by path, so the
/// *first* load of a path fixes its settings and later ones quietly inherit
/// them — two unordered `Startup` systems loading this with different samplers
/// is a race, and the losing outcome is bilinear-blurred voxels for the
/// session. One loader means there is nothing to win.
pub fn load_atlas(asset_server: &AssetServer) -> Handle<Image> {
    asset_server.load_builder().with_settings(atlas_settings).load(ATLAS_PATH)
}

/// The block *mega* atlas, one 1024² tile per index stacked vertically. Load
/// it only through [`load_mega_atlas`].
pub const MEGA_ATLAS_PATH: &str = "blocks_mega.png";

/// Linear + repeat: `atlas.wgsl` samples at `face_uv / 16` with no `fract`, so
/// the texture wraps on its own and filters smoothly at 64 px/block. No mips
/// are generated (accepted first pass: some shimmer at distance). Main-world
/// only — [`promote_block_textures`] releases it to the render world after
/// reinterpreting it as an array.
fn mega_atlas_settings(s: &mut ImageLoaderSettings) {
    s.sampler = ImageSampler::Descriptor(ImageSamplerDescriptor {
        address_mode_u: ImageAddressMode::Repeat,
        address_mode_v: ImageAddressMode::Repeat,
        mag_filter: ImageFilterMode::Linear,
        min_filter: ImageFilterMode::Linear,
        mipmap_filter: ImageFilterMode::Linear,
        ..default()
    });
    s.asset_usage = RenderAssetUsages::MAIN_WORLD;
}

/// Load the terrain mega atlas.
///
/// Same one-loader-per-path rule as [`load_atlas`], and for the same reason:
/// `AssetServer` keys by path, so the first load fixes the settings. The two
/// atlases are deliberately separate assets — terrain wants a repeating,
/// linearly filtered array, the inventory icons want a nearest-sampled 2D grid
/// — and sharing one handle between them cannot give both.
pub fn load_mega_atlas(asset_server: &AssetServer) -> Handle<Image> {
    asset_server.load_builder().with_settings(mega_atlas_settings).load(MEGA_ATLAS_PATH)
}

/// Build the atlas texture and the faces-table buffer.
fn setup_gpu_assets(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut buffers: ResMut<Assets<ShaderBuffer>>,
    blocks: Res<Blocks>,
) {
    let texture = load_mega_atlas(&asset_server);

    let faces: Vec<UVec4> = blocks.0.faces_table().into_iter().map(UVec4::from_array).collect();
    let faces_buf = buffers.add(ShaderBuffer::from(faces));

    commands.insert_resource(AtlasAssets { texture, promoted: false });
    commands.insert_resource(FacesTable(faces_buf));
}

/// Once `blocks_mega.png` has decoded, reinterpret the stacked image as a
/// `MEGA_LAYERS`-layer texture array, release it to the render world, and
/// publish the handle the terrain bind group waits on.
fn promote_block_textures(
    mut commands: Commands,
    mut atlas: ResMut<AtlasAssets>,
    mut images: ResMut<Assets<Image>>,
) {
    if atlas.promoted {
        return;
    }
    let Some(mut image) = images.get_mut(&atlas.texture) else { return };
    if let Err(e) = image.reinterpret_stacked_2d_as_array(MEGA_LAYERS) {
        // Wrong height for the layer count: the PNG and MEGA_LAYERS disagree.
        // Nothing will draw; say why loudly rather than every frame.
        error!("blocks_mega.png is not {MEGA_LAYERS} stacked 1024² tiles: {e:?}");
        atlas.promoted = true;
        return;
    }
    image.asset_usage = RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD;
    atlas.promoted = true;
    commands.insert_resource(crate::world_draw::ExtractedAtlas(atlas.texture.clone()));
}

// ---------- Render world ----------

#[derive(Resource)]
pub(crate) struct VoxelMeshPipeline {
    layout: BindGroupLayoutDescriptor,
    clear: CachedComputePipelineId,
    mesh: CachedComputePipelineId,
    finalize: CachedComputePipelineId,
}

/// This frame's remesh batch: the jobs buffer holds the mesh-slot ids, the
/// bind group binds it with the pools.
#[derive(Resource, Default)]
pub(crate) struct VoxelMeshJobs {
    jobs: Option<RawBufferVec<u32>>,
    bind_group: Option<BindGroup>,
    count: u32,
}

fn init_pipeline(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    pipeline_cache: Res<PipelineCache>,
) {
    let layout = BindGroupLayoutDescriptor::new(
        "voxel_mesh_layout",
        &BindGroupLayoutEntries::sequential(
            ShaderStages::COMPUTE,
            (
                storage_buffer_read_only_sized(false, None), // voxel pool
                storage_buffer_sized(false, None),           // quad pool (rw)
                storage_buffer_read_only_sized(false, None), // block faces
                storage_buffer_sized(false, None),           // indirect args (rw, atomic)
                storage_buffer_read_only_sized(false, None), // jobs
            ),
        ),
    );
    let shader = asset_server.load("shaders/voxel_mesh.wgsl");
    let pipe = |entry: &'static str| ComputePipelineDescriptor {
        label: Some(format!("voxel_{entry}").into()),
        layout: vec![layout.clone()],
        shader: shader.clone(),
        entry_point: Some(entry.into()),
        ..default()
    };
    let clear = pipeline_cache.queue_compute_pipeline(pipe("clear_counter"));
    let mesh = pipeline_cache.queue_compute_pipeline(pipe("mesh_slice"));
    let finalize = pipeline_cache.queue_compute_pipeline(pipe("finalize_mesh"));
    commands.insert_resource(VoxelMeshPipeline { layout, clear, mesh, finalize });
    commands.insert_resource(VoxelMeshJobs::default());
}

/// Upload this frame's dirty-slot list and build the batch bind group.
#[allow(clippy::too_many_arguments)]
fn prepare_jobs(
    mut jobs: ResMut<VoxelMeshJobs>,
    mut ops: ResMut<ExtractedPoolOps>,
    pipeline: Res<VoxelMeshPipeline>,
    pools: Option<Res<ChunkPools>>,
    render_device: Res<RenderDevice>,
    render_queue: Res<RenderQueue>,
    pipeline_cache: Res<PipelineCache>,
    faces: Option<Res<FacesTable>>,
    buffers: Res<RenderAssets<GpuShaderBuffer>>,
) {
    jobs.bind_group = None;
    jobs.count = 0;
    let Some(pools) = pools else { return };
    let Some(faces) = faces else { return };
    if ops.1.is_empty() {
        return;
    }
    let Some(faces_buf) = buffers.get(&faces.0) else {
        return; // faces table not resident yet; the dirty list carries over
    };
    // Never consume jobs the node can't dispatch: during startup the compute
    // pipelines compile asynchronously, and a batch taken before they're
    // ready would be silently dropped — chunks that never mesh (the join
    // burst races pipeline compilation on warm servers).
    if pipeline_cache.get_compute_pipeline(pipeline.clear).is_none()
        || pipeline_cache.get_compute_pipeline(pipeline.mesh).is_none()
        || pipeline_cache.get_compute_pipeline(pipeline.finalize).is_none()
    {
        return;
    }
    let dirty = std::mem::take(&mut ops.1);

    let jobs_vec = jobs.jobs.get_or_insert_with(|| RawBufferVec::new(BufferUsages::STORAGE));
    jobs_vec.clear();
    for slot in &dirty {
        jobs_vec.push(*slot);
    }
    jobs_vec.write_buffer(&render_device, &render_queue);

    let layout = pipeline_cache.get_bind_group_layout(&pipeline.layout);
    let bind_group = render_device.create_bind_group(
        None,
        &layout,
        &BindGroupEntries::sequential((
            pools.voxels.as_entire_buffer_binding(),
            pools.quads.as_entire_buffer_binding(),
            faces_buf.buffer.as_entire_buffer_binding(),
            pools.indirect.as_entire_buffer_binding(),
            jobs.jobs.as_ref().unwrap().buffer().unwrap().as_entire_buffer_binding(),
        )),
    );
    jobs.bind_group = Some(bind_group);
    jobs.count = dirty.len() as u32;
}

/// Greedy-mesh every dirty slot into the shared quad pool.
pub(crate) fn voxel_mesh_pass(
    mut render_context: RenderContext,
    pipeline_cache: Res<PipelineCache>,
    pipeline: Res<VoxelMeshPipeline>,
    jobs: Option<Res<VoxelMeshJobs>>,
) {
    let Some(jobs) = jobs else { return };
    let Some(bind_group) = &jobs.bind_group else {
        return;
    };
    let (Some(clear), Some(mesh), Some(finalize)) = (
        pipeline_cache.get_compute_pipeline(pipeline.clear),
        pipeline_cache.get_compute_pipeline(pipeline.mesh),
        pipeline_cache.get_compute_pipeline(pipeline.finalize),
    ) else {
        return;
    };

    let mut pass = render_context
        .command_encoder()
        .begin_compute_pass(&ComputePassDescriptor { label: Some("voxel_mesh"), ..default() });
    pass.set_bind_group(0, bind_group, &[]);
    pass.set_pipeline(clear);
    pass.dispatch_workgroups(jobs.count, 1, 1);
    pass.set_pipeline(mesh);
    pass.dispatch_workgroups(3, 33, jobs.count);
    pass.set_pipeline(finalize);
    pass.dispatch_workgroups(jobs.count, 1, 1);
}

#[cfg(test)]
mod tests {
    use super::*;
    use bevy::image::ImageFilterMode;

    /// The atlas must pin its own sampler rather than inherit the `ImagePlugin`
    /// default, which is linear and blurs every voxel face.
    #[test]
    fn atlas_samples_nearest() {
        let mut s = ImageLoaderSettings::default();
        atlas_settings(&mut s);
        let ImageSampler::Descriptor(d) = s.sampler else {
            panic!("atlas inherits the ImagePlugin default sampler");
        };
        assert_eq!(d.mag_filter, ImageFilterMode::Nearest, "magnification");
        assert_eq!(d.min_filter, ImageFilterMode::Nearest, "minification");
        assert_eq!(d.mipmap_filter, ImageFilterMode::Nearest, "mipmap");
    }

    /// A second load of the atlas by literal path would race [`load_atlas`] and
    /// could win with the default sampler, so the path belongs in exactly one
    /// place. This is the test that catches the bug coming back: the symptom is
    /// a startup-order race, so a normal run may reproduce it only sometimes.
    ///
    /// The needle is built from [`ATLAS_PATH`] rather than written out, so this
    /// test does not count itself.
    #[test]
    fn the_atlas_path_is_written_once() {
        let needle = format!("{ATLAS_PATH:?}");
        let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut hits = Vec::new();
        let mut stack = vec![src.clone()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).unwrap().flatten() {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension() == Some(std::ffi::OsStr::new("rs")) {
                    let text = std::fs::read_to_string(&path).unwrap();
                    for (n, line) in text.lines().enumerate() {
                        if line.contains(&needle) && !line.trim_start().starts_with("//") {
                            let rel = path.strip_prefix(&src).unwrap();
                            hits.push(format!("{}:{}", rel.display(), n + 1));
                        }
                    }
                }
            }
        }
        assert_eq!(hits.len(), 1, "load the atlas via `load_atlas`, not by path; found {hits:?}");
    }

    /// The global default backs up [`load_atlas`] for anything loaded without
    /// settings. Losing it is silent — nothing fails, textures just go blurry —
    /// so pin it here.
    #[test]
    fn the_app_sets_the_global_nearest_default() {
        let main = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/main.rs");
        let text = std::fs::read_to_string(main).unwrap();
        assert!(
            text.contains("ImagePlugin::default_nearest()"),
            "DefaultPlugins must .set(ImagePlugin::default_nearest())"
        );
        // The plugin default is linear, so the call above is the only thing
        // standing between a settings-less load and bilinear filtering.
        assert_eq!(
            ImagePlugin::default_nearest().default_sampler.mag_filter,
            ImageFilterMode::Nearest
        );
    }
}
